global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: i18n-registration-bot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - bot:8080
